id-fed
Summary:

- Support for OIDC  to 3 major hyperscalars.
- Added robot test `ID Fed AWS S3 Buckets List`.
- Added robot test `ID Fed Azure VNETs List`.
- Added robot test `ID Fed Google Buckets List`.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -546,6 +546,9 @@ jobs:
     needs:
       - linuxbuild
       - test_python_package_build
+    permissions:
+      id-token: write
+      contents: read
     runs-on: ubuntu-22-04-m
     strategy:
       matrix:
@@ -759,6 +762,58 @@ jobs:
       run: |
         cat ./test/robot/foreign-integration-traffic-lights/tmp/* || true
     
+    - name: ID Fed - configure AWS credentials (OIDC)
+      if: ((startsWith(github.ref_name, 'build-traffic-lights') && github.ref_type == 'tag') || (github.repository == 'stackql/stackql' && github.event_name == 'push' && github.ref == 'refs/heads/main')) && matrix.registry == 'test/registry'
+      uses: aws-actions/configure-aws-credentials@v4
+      with:
+        role-to-assume: ${{ secrets.STACKQL_ID_FED_AWS_ROLE_ARN }}
+        aws-region: us-east-1
+
+    - name: ID Fed - authenticate to Google Cloud (OIDC)
+      if: ((startsWith(github.ref_name, 'build-traffic-lights') && github.ref_type == 'tag') || (github.repository == 'stackql/stackql' && github.event_name == 'push' && github.ref == 'refs/heads/main')) && matrix.registry == 'test/registry'
+      uses: google-github-actions/auth@v2
+      with:
+        workload_identity_provider: ${{ secrets.STACKQL_ID_FED_GCP_WORKLOAD_IDENTITY_PROVIDER }}
+        service_account: ${{ secrets.STACKQL_ID_FED_GCP_SERVICE_ACCOUNT }}
+
+    - name: ID Fed - login to Azure (OIDC)
+      if: ((startsWith(github.ref_name, 'build-traffic-lights') && github.ref_type == 'tag') || (github.repository == 'stackql/stackql' && github.event_name == 'push' && github.ref == 'refs/heads/main')) && matrix.registry == 'test/registry'
+      uses: azure/login@v2
+      with:
+        client-id: ${{ secrets.STACKQL_ID_FED_AZURE_CLIENT_ID }}
+        tenant-id: ${{ secrets.STACKQL_ID_FED_AZURE_TENANT_ID }}
+        subscription-id: ${{ secrets.AZURE_INTEGRATION_TESTING_SUB_ID }}
+
+    - name: Run id-fed traffic light robot integration tests
+      if: ((startsWith(github.ref_name, 'build-traffic-lights') && github.ref_type == 'tag') || (github.repository == 'stackql/stackql' && github.event_name == 'push' && github.ref == 'refs/heads/main')) && matrix.registry == 'test/registry'
+      env:
+        PYTHONPATH: '${{ env.PYTHONPATH }}:${{ github.workspace }}/test/python'
+        AZURE_TARGET_SUBSCRIPTION_ID: ${{ secrets.AZURE_INTEGRATION_TESTING_SUB_ID }}
+        GODEBUG: netdns=go
+      run: |
+        echo "## Stray flask apps to be killed before robot tests ##"
+        pgrep -f flask | xargs kill -9 || true
+        echo "## End ##"
+        if python cicd/python/build.py --robot-test-id-fed-traffic-lights-integration; then
+          echo "✅ ID-FED traffic light robot integration tests **all** passed"
+        else
+          rv="$?"
+          echo "🟡 **some** ID-FED traffic light robot integration tests failed code = $rv"
+        fi
+        {
+          echo "ID_FED_TRAFFIC_LIGHTS_COMPLETED=true"
+        } >> "$GITHUB_ENV"
+
+    - name: Output from id-fed traffic lights integration tests
+      if: env.ID_FED_TRAFFIC_LIGHTS_COMPLETED == 'true'
+      run: |
+        cat ./test/robot/reports-id-fed-traffic-lights/output.xml || true
+
+    - name: Output from id-fed traffic lights tmp dir
+      if: env.ID_FED_TRAFFIC_LIGHTS_COMPLETED == 'true'
+      run: |
+        cat ./test/robot/id-fed-traffic-lights/tmp/* || true
+
     - name: Generate hosts file and nginx materials
       env:
         BUILDCOMMITSHA: ${{github.sha}}
