try-the-builder

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -476,3 +476,57 @@ jobs:
       with:
         name: stackql_darwin_arm64
         path: build/stackql
+
+  dockerbuild:
+    name: Docker Build
+    runs-on: ubuntu-latest
+    steps:
+    
+    - name: Git Ref Parse
+      id: git_ref_parse
+      run: |
+          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
+          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
+          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
+    
+    - name: Install psql
+      run: |
+          sudo apt-get update
+          sudo apt-get install --yes --no-install-recommends \
+            postgresql-client \
+            ca-certificates
+
+    - name: Check out code into the Go module directory
+      uses: actions/checkout@v2
+
+    - name: Install Python dependencies
+      run: |
+        pip3 install PyYaml
+        pip3 install robotframework
+    
+    - name: Generate rewritten registry for simulations
+      run: |
+        python3 test/python/registry-rewrite.py --replacement-host=host.docker.internal
+
+    - name: Mock Server Download
+      run: |
+        mvn \
+        org.apache.maven.plugins:maven-dependency-plugin:3.0.2:copy \
+        -Dartifact=org.mock-server:mockserver-netty:5.12.0:jar:shaded \
+        -DoutputDirectory=test/downloads
+
+    - name: Pull Docker image for cache purposes
+      run: |
+        docker pull stackql/stackql:latest || echo 'could not pull image for cache purposes'
+        docker-compose build stackqlsrv
+
+    - name: Run robot mocked functional tests
+      if: success()
+      run: |
+        robot --variable EXECUTION_PLATFORM:docker test/robot/functional
+    
+    - name: Run robot integration tests
+      if: success() && startsWith(${{ steps.git_ref_parse.outputs.SOURCE_TAG }}, 'build-release')
+      run: |
+        robot --variable EXECUTION_PLATFORM:docker test/robot/integration
+
