another-cleanup

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -26,6 +26,10 @@ jobs:
     name: Windows Build
     runs-on: windows-latest
     steps:
+
+    - name: Check out code into the Go module directory
+      uses: actions/checkout@v2
+
     - name: Set up Go 1.x
       uses: actions/setup-go@v2
       with:
@@ -51,9 +55,6 @@ jobs:
     - name: Get rid of disruptive line endings before checkout
       run: |
         git config --global core.autocrlf false
-
-    - name: Check out code into the Go module directory
-      uses: actions/checkout@v2
 
     - name: Install Python dependencies
       run: |
@@ -166,6 +167,10 @@ jobs:
     name: Linux Build
     runs-on: ubuntu-latest
     steps:
+
+    - name: Check out code into the Go module directory
+      uses: actions/checkout@v2
+
     - name: Set up Go 1.x
       uses: actions/setup-go@v2
       with:
@@ -190,9 +195,6 @@ jobs:
       run: |
           sudo apt-get update
           sudo apt-get install --yes --no-install-recommends postgresql-client
-
-    - name: Check out code into the Go module directory
-      uses: actions/checkout@v2
 
     - name: Install Python dependencies
       run: |
@@ -300,6 +302,9 @@ jobs:
       with:
         go-version: ^1.18
       id: go
+
+    - name: Check out code into the Go module directory
+      uses: actions/checkout@v2
     
     - name: Git Ref Parse
       id: git_ref_parse
@@ -307,9 +312,6 @@ jobs:
           echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
           echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
           echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
-
-    - name: Check out code into the Go module directory
-      uses: actions/checkout@v2
 
     - name: Install Python dependencies
       run: |
@@ -481,6 +483,9 @@ jobs:
     name: Docker Build
     runs-on: ubuntu-latest
     steps:
+
+    - name: Check out code into the Go module directory
+      uses: actions/checkout@v2
     
     - name: Git Ref Parse
       id: git_ref_parse
@@ -495,9 +500,6 @@ jobs:
           sudo apt-get install --yes --no-install-recommends \
             postgresql-client \
             ca-certificates
-
-    - name: Check out code into the Go module directory
-      uses: actions/checkout@v2
 
     - name: Install Python dependencies
       run: |
@@ -517,8 +519,8 @@ jobs:
 
     - name: Pull Docker image for cache purposes
       run: |
-        docker pull stackql/stackql:latest || echo 'could not pull image for cache purposes'
-        docker-compose build stackqlsrv
+        docker pull stackql/stackql:latest || echo 'could not pull image for cache purposes' \
+        && docker-compose build stackqlsrv
 
     - name: Create certificates for robot tests
       run: |
