automation-and-testing-for-docker
Summary

- Docker builder in GitHub Actions.
- Robot tests for docker.
- Docker quickstart in README.

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -26,6 +26,10 @@ jobs:
     name: Windows Build
     runs-on: windows-latest
     steps:
+
+    - name: Check out code into the Go module directory
+      uses: actions/checkout@v2
+
     - name: Set up Go 1.x
       uses: actions/setup-go@v2
       with:
@@ -51,9 +55,6 @@ jobs:
     - name: Get rid of disruptive line endings before checkout
       run: |
         git config --global core.autocrlf false
-
-    - name: Check out code into the Go module directory
-      uses: actions/checkout@v2
 
     - name: Install Python dependencies
       run: |
@@ -166,6 +167,10 @@ jobs:
     name: Linux Build
     runs-on: ubuntu-latest
     steps:
+
+    - name: Check out code into the Go module directory
+      uses: actions/checkout@v2
+
     - name: Set up Go 1.x
       uses: actions/setup-go@v2
       with:
@@ -190,9 +195,6 @@ jobs:
       run: |
           sudo apt-get update
           sudo apt-get install --yes --no-install-recommends postgresql-client
-
-    - name: Check out code into the Go module directory
-      uses: actions/checkout@v2
 
     - name: Install Python dependencies
       run: |
@@ -300,6 +302,9 @@ jobs:
       with:
         go-version: ^1.18
       id: go
+
+    - name: Check out code into the Go module directory
+      uses: actions/checkout@v2
     
     - name: Git Ref Parse
       id: git_ref_parse
@@ -307,9 +312,6 @@ jobs:
           echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
           echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
           echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
-
-    - name: Check out code into the Go module directory
-      uses: actions/checkout@v2
 
     - name: Install Python dependencies
       run: |
@@ -476,3 +478,63 @@ jobs:
       with:
         name: stackql_darwin_arm64
         path: build/stackql
+
+  dockerbuild:
+    name: Docker Build
+    runs-on: ubuntu-latest
+    steps:
+
+    - name: Check out code into the Go module directory
+      uses: actions/checkout@v2
+    
+    - name: Git Ref Parse
+      id: git_ref_parse
+      run: |
+          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
+          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
+          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
+    
+    - name: Install psql
+      run: |
+          sudo apt-get update
+          sudo apt-get install --yes --no-install-recommends \
+            postgresql-client \
+            ca-certificates
+
+    - name: Install Python dependencies
+      run: |
+        pip3 install PyYaml
+        pip3 install robotframework
+    
+    - name: Generate rewritten registry for simulations
+      run: |
+        python3 test/python/registry-rewrite.py --replacement-host=host.docker.internal
+
+    - name: Mock Server Download
+      run: |
+        mvn \
+        org.apache.maven.plugins:maven-dependency-plugin:3.0.2:copy \
+        -Dartifact=org.mock-server:mockserver-netty:5.12.0:jar:shaded \
+        -DoutputDirectory=test/downloads
+
+    - name: Pull Docker image for cache purposes
+      run: |
+        docker pull stackql/stackql:latest || echo 'could not pull image for cache purposes' \
+        && docker-compose build stackqlsrv
+
+    - name: Create certificates for robot tests
+      run: |
+        openssl req -x509 -keyout test/server/mtls/credentials/pg_server_key.pem -out test/server/mtls/credentials/pg_server_cert.pem -config test/server/mtls/openssl.cnf -days 365
+        openssl req -x509 -keyout test/server/mtls/credentials/pg_client_key.pem -out test/server/mtls/credentials/pg_client_cert.pem -config test/server/mtls/openssl.cnf -days 365
+        openssl req -x509 -keyout test/server/mtls/credentials/pg_rubbish_key.pem -out test/server/mtls/credentials/pg_rubbish_cert.pem -config test/server/mtls/openssl.cnf -days 365 
+
+    - name: Run robot mocked functional tests
+      if: success()
+      run: |
+        robot --variable EXECUTION_PLATFORM:docker test/robot/functional
+    
+    - name: Run robot integration tests
+      if: success() && startsWith(${{ steps.git_ref_parse.outputs.SOURCE_TAG }}, 'build-release')
+      run: |
+        robot --variable EXECUTION_PLATFORM:docker test/robot/integration
+
